"""add_note_prices

Revision ID: 1c78b916b679
Revises: 6095ed371b14
Create Date: 2025-12-01 03:17:01.219285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "1c78b916b679"
down_revision: Union[str, Sequence[str], None] = "6095ed371b14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("price", sa.Integer(), nullable=False))
    op.add_column("note", sa.Column("is_free", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note", "is_free")
    op.drop_column("note", "price")
    # ### end Alembic commands ###
