"""add_purchase_model

Revision ID: 6095ed371b14
Revises: d65f4b2f9106
Create Date: 2025-12-01 03:16:18.890536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "6095ed371b14"
down_revision: Union[str, Sequence[str], None] = "d65f4b2f9106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("price_paid", sa.Integer(), nullable=False),
        sa.Column("purchased_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_note_id"), "purchase", ["note_id"], unique=False)
    op.create_index(op.f("ix_purchase_user_id"), "purchase", ["user_id"], unique=False)
    op.alter_column(
        "user",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_purchase_user_id"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_note_id"), table_name="purchase")
    op.drop_table("purchase")
    # ### end Alembic commands ###
