"""add points column to user

Revision ID: 73d4b5f51b9f
Revises: 9666c40d4524
Create Date: 2025-11-30 01:24:28.402284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "73d4b5f51b9f"
down_revision: Union[str, Sequence[str], None] = "9666c40d4524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rating_author_id"), "rating", ["author_id"], unique=False)
    op.create_index(op.f("ix_rating_note_id"), "rating", ["note_id"], unique=False)
    # Add new columns with server defaults so existing rows (if any) are populated
    op.add_column(
        "note",
        sa.Column(
            "course_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "note",
        sa.Column(
            "semester",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "note", sa.Column("downloads", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "note", sa.Column("views", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "user",
        sa.Column("points", sa.Integer(), nullable=False, server_default="10000"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "points")
    op.drop_column("note", "views")
    op.drop_column("note", "downloads")
    op.drop_column("note", "semester")
    op.drop_column("note", "course_name")
    op.drop_index(op.f("ix_rating_note_id"), table_name="rating")
    op.drop_index(op.f("ix_rating_author_id"), table_name="rating")
    op.drop_table("rating")
    # ### end Alembic commands ###
