"""user profile preferences

Revision ID: 9666c40d4524
Revises: ebc20a3800e2
Create Date: 2025-10-28 03:58:00.911945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9666c40d4524"
down_revision: Union[str, Sequence[str], None] = "ebc20a3800e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note",
        sa.Column("object_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("note", "file_url")
    op.add_column(
        "user", sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("user", sa.Column("is_profile_public", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("show_email", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_sub"), "user", ["sub"], unique=False)
    op.drop_column("user", "auth_provider")
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column("auth_provider", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_user_sub"), table_name="user")
    op.drop_column("user", "show_email")
    op.drop_column("user", "is_profile_public")
    op.drop_column("user", "bio")
    op.drop_column("user", "display_name")
    op.drop_column("user", "avatar_url")
    op.drop_column("user", "sub")
    op.add_column(
        "note", sa.Column("file_url", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("note", "object_key")
    # ### end Alembic commands ###
