"""add_role_is_admin_to_user

Revision ID: d65f4b2f9106
Revises: 73d4b5f51b9f
Create Date: 2025-12-01 02:59:11.600301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "d65f4b2f9106"
down_revision: Union[str, Sequence[str], None] = "73d4b5f51b9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "note",
        "course_name",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "semester",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "downloads",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "views",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "user",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.alter_column("user", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user",
        "points",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.alter_column(
        "user",
        "points",
        existing_type=sa.INTEGER(),
        server_default=sa.text("10000"),
        existing_nullable=False,
    )
    op.alter_column("user", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "is_admin")
    op.alter_column(
        "note",
        "views",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "downloads",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "semester",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "note",
        "course_name",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
